
var JQuerySlider_init = {
   "align":"left",
   "auto":true,
   "hideOnMouseOut":true,
   "vertical":false,
   "ease":"linear",
   "continuous":true,
   "loop":true,
   "sliderEffect":"slide",
   "speed":"1000",
   "fadeDuration":"1000",
   "pause":"1000",
   "stopAtInteraction":"false",
   "resumeDuration":"3000",
   "innernavbaritem.spacing":"0px",
   "innernumbers.spacing":"0px",
   
   "innerbutton.back.opacity":1,
   "innerbutton.back.hideOnMouseOut":false,
   "innerbutton.back.mouseOutEffect":"fadeIn",
   "innerbutton.back.mouseOutEffectDuration":"1000",
   "innerbutton.back.mouseOutEffectEasing":"linear",
   
   
   "innerbutton.back.halign":"left",
   "innerbutton.back.valign":"middle",
   "innerbutton.back.left":"10px",
   "innerbutton.back.top":"0px",
   
   "innerbutton.next.opacity":1,
   "innerbutton.next.hideOnMouseOut":false,
   "innerbutton.next.mouseOutEffect":"fadeIn",
   "innerbutton.next.mouseOutEffectDuration":"1000",
   "innerbutton.next.mouseOutEffectEasing":"linear",
   
   
   "innerbutton.next.halign":"left",
   "innerbutton.next.valign":"top",
   "innerbutton.next.left":"0px",
   "innerbutton.next.top":"0px",
   
   "innerplaypause.opacity":1,
   "innerplaypause.hideOnMouseOut":false,
   "innerplaypause.mouseOutEffect":"fadeIn",
   "innerplaypause.mouseOutEffectDuration":"1000",
   "innerplaypause.mouseOutEffectEasing":"linear",
    
   "innerplaypause.halign":"left",
   "innerplaypause.valign":"top",
   "innerplaypause.left":"0px",
   "innerplaypause.top":"0px",
   
   
   "innernavbar.hideOnMouseOut":false,
   "innernavbar.mouseOutEffect":"fadeIn",
   "innernavbar.mouseOutEffectDuration":"1000",
   "innernavbar.mouseOutEffectEasing":"linear",
   
   "innernavbar.halign":"left",
   "innernavbar.valign":"top",
   "innernavbar.left":"0px",
   "innernavbar.top":"0px",
   "innernavbaritem.orientation":"horizontal",
 
   "innerbullets.valign":"middle",
   "innerbullets.halign":"left",
   "innerbullets.left":"40px",
   "innerbullets.hideOnMouseOut":false,
   "innerbullets.mouseOutEffect":"fadeIn",
   "innerbullets.mouseOutEffectEasing":"linear",
   "innerbullets.mouseOutEffectDuration":"1000",
   "innerbulletsitem.orientation":"horizontal",
   
   "innernumbers.valign":"middle",
   "innernumbers.halign":"left",
   "innernumbers.left":"40px",
   "innernumbers.hideOnMouseOut":false,
   "innernumbers.mouseOutEffect":"fadeIn",
   "innernumbers.mouseOutEffectEasing":"linear",
   "innernumbers.mouseOutEffectDuration":"1000",
   "innernumbersitem.orientation":"horizontal",
   
   "content_paragraph.opacity": "1",
   "content_subheader.opacity": "1",
   "content_header.opacity": "1",
   
   "innernavbar.scrollerType" : "noScroll"
};

(function(k){k.browser.msie&&parseInt(k.browser.version,10);k.fn.sudoSlider=function(e){var l=!0,c=!l;e=k.extend({prevNext:l,prevHtml:'<a href="#" class="prevBtn"> previous </a>',nextHtml:'<a href="#" class="nextBtn"> next </a>',controlsShow:l,controlsAttr:'id="controls"',controlsFadeSpeed:"400",controlsFade:l,insertAfter:l,firstShow:c,firstHtml:'<a href="#" class="firstBtn"> first </a>',lastShow:c,lastHtml:'<a href="#" class="lastBtn"> last </a>',numericAttr:'class="controls"',numericText:["1"],
vertical:c,speed:"800",ease:"swing",auto:c,pause:"2000",continuous:c,clickableAni:c,numeric:c,updateBefore:c,history:c,speedhistory:"400",autoheight:l,customLink:c,fade:c,crossFade:l,fadespeed:"1000",ajax:c,loadingText:"Loading Content...",preloadAjax:c,startSlide:c,ajaxLoadFunction:c,beforeAniFunc:c,afterAniFunc:c,uncurrentFunc:c,currentFunc:c,autowidth:l,slideCount:1,resumePause:c},e);var b=[e.controlsShow,e.controlsFadeSpeed,e.controlsFade,e.insertAfter,e.firstShow,e.lastShow,e.vertical,e.speed,
e.ease,e.auto,e.pause,e.continuous,e.prevNext,e.numeric,e.numericAttr,e.numericText,e.clickableAni,e.history,e.speedhistory,e.autoheight,e.customLink,e.fade,e.crossFade,e.fadespeed,e.updateBefore,e.ajax,e.preloadAjax,e.startSlide,e.ajaxLoadFunction,e.beforeAniFunc,e.afterAniFunc,e.uncurrentFunc,e.currentFunc,e.prevHtml,e.nextHtml,e.loadingText,e.firstHtml,e.controlsAttr,e.lastHtml,e.autowidth,e.slideCount,e.resumePause],m=this;return this.each(function(){function e(d,f){A=c;T=l;s=d.children("ul");
v=r=s.children("li");q=r.length;if(b[25]&&(0==s.length&&(d.append("<ul></ul>"),s=d.children("ul")),b[25].length>q)){for(var g=1;g<=b[25].length-q;g++)s.append("<li><p>"+b[35]+"</p></li>");r=s.children("li");q=r.length}x=h=0;n=q-1;t=l;G=w=U=c;O=[];A=V=c;W=screen.fontSmoothingEnabled;d.css("overflow","hidden");"static"==d.css("position")&&d.css("position","relative");r.css({"float":"left",display:"block"});for(g=0;g<q;g++)void 0==b[15][g]&&(b[15][g]=g+1),b[25]&&void 0==b[25][g]&&(b[25][g]=c);if(b[11]&&
!b[21]){a=0;if(b[6])for(g=b[40];1<=g;g--){var z=r.eq(-b[40]+g-1).clone();a+=z.outerWidth(l);z.css("margin-top","-"+a+"px");s.prepend(z);s.append(r.eq(b[40]-g).clone().css({"z-index":"0"}))}if(!b[6])for(g=b[40];1<=g;g--)z=r.eq(-b[40]+g-1).clone(),a+=z.outerWidth(l),z.css("margin-left","-"+a+"px"),s.prepend(z),s.append(r.eq(b[40]-g).clone().css({"z-index":"0"}));v=s.children("li");b[25]&&(b[25][0]&&D(0,1==b[27]?l:c,0,c),b[25][0]=c,b[25][n]&&D(n,b[27]==n?l:c,0,c),b[25][n]=c,1<b[40]&&X(l))}Y();v=s.children("li");
u=c;if(b[0]){u=k("<span "+b[37]+"></span>");b[3]?k(d).after(u):k(d).before(u);if(b[13])for(V=u.prepend("<ol "+b[14]+"></ol>").children(),z=b[11]?1:b[40],g=0;g<q-z+1;g++)O[g]=k(document.createElement("li")).attr({rel:g+1}).html('<a href="#"><span>'+b[15][g]+"</span></a>").appendTo(V).click(function(){E(k(this).attr("rel")-1,l);return c});b[4]&&P(b[36],"first");b[5]&&P(b[38],"last");b[12]&&(P(b[34],"next"),P(b[33],"prev"))}b[26]&&X(l);b[1]=H(b[1]);b[7]=H(b[7]);b[10]=H(b[10]);b[18]=H(b[18]);b[23]=H(b[23]);
b[40]=parseInt(b[40],10);b[20]&&k(b[20]).live("click",function(){if(a=k(this).attr("rel"))"stop"==a?(b[9]=c,clearTimeout(B),I=c):"start"==a?(b[11]||m.setOption("continuous",l),B=J(b[10]),b[9]=l):"block"==a?t=c:"unblock"==a?t=l:t&&E(a==parseInt(a)?a-1:a,l);return c});b[9]&&(B=J(b[10]));f?C(f,c,c,c):b[17]?k.address.init(function(b){f||C(ba(b.value),c,c,c)}).change(function(b){b=ba(b.value);b!=h&&E(b,c)}):b[27]?C(b[27]-1,c,c,c):C(0,c,c,c)}function X(d){for(var f=0;f<=n;f++)b[25][f]&&(D(f,b[27]==f&&d?
l:c,0,c),b[25][f]=c)}function Y(){a=0;if(b[6]){for(var d=-1;d<=q;d++)a+=r.eq(d).outerHeight(l);s.height(4*a)}else{for(d=-1;d<=q;d++)a+=r.eq(d).outerWidth(l);s.width(4*a)}}function J(b){I=l;return setTimeout(function(){E("next",c)},b)}function H(b){if(parseInt(b))var f=parseInt(b);else switch(f=400,b){case "fast":case "normal":case "medium":case "slow":f=600}return f}function P(b,f){return k(b).prependTo(u).click(function(){E(f,l);return c})}function E(d,f){if(!A){if(b[9]){var g=b[7];w&&b[22]?g=parseInt(0.6*
g):w&&(g=0);f?(clearTimeout(B),I=c,b[41]&&(B=J(g+b[41]))):B=J(b[10]+g)}b[21]?ca(d,f):(b[11]&&(a=h,0>a&&(a+=q),a>n&&(a-=q),d==a+1&&(d="next"),d==a-1&&(d="prev"),0==a&&d==n&&(d="prev"),a==n&&0==d&&(d="next")),C(d,f,l,c))}}function Z(b,f){b.each(function(){var b="img"===this.tagName.toLowerCase()?k(this):k("img",this),d=this,c=0,h=function(){"function"===typeof f&&f(d)};b.length?b.each(function(){var d=this,f=function(f){d.complete||"complete"==d.readyState&&"readystatechange"==f.type?++c===b.length&&
h():void 0===d.readyState&&k(d).attr("src",k(d).attr("src"))};k(d).bind("load readystatechange",function(b){f(b)});f({type:"readystatechange"})}):h()})}function ka(b){var f=b.length,g=b.substr(f-4,4);return".jpg"==g||".png"==g||".bmp"==g||".gif"==g||".jpeg"==b.substr(f-5,5)?l:c}function $(d){d=parseInt(d>n?d=0:0>d?d=n+d+1:d)+1;for(var f=0;f<O.length;f++)da(O[f],d);b[20]&&da(b[20],d)}function da(d,f){k(d).filter(".current").removeClass("current").each(function(){k.isFunction(b[31])&&b[31].call(this,
k(this).attr("rel"))});k(d).filter(function(){return k(this).attr("rel")==f}).addClass("current").each(function(d){k.isFunction(b[32])&&b[32].call(this,f)})}function ba(d){for(var f=0,g=0;g<=q;g+=1)b[15][g]==d&&(f=g);return f}function K(d,f){b[19]&&la(d,f);b[39]&&ma(d,f)}function la(b,f){y.ready(function(){b==q&&(b=0);var g=r.eq(b).height();0!=g&&ea(g,f);Z(r.eq(b),function(b){y.ready(function(){g=k(b).height();0!=g&&ea(g,f)})})})}function ma(b,f){y.ready(function(){b==q&&(b=0);var g=r.eq(b).width();
0!=g&&fa(g,f);Z(r.eq(b),function(b){y.ready(function(){g=k(b).width();0!=g&&fa(g,f)})})})}function fa(d,f){y.animate({width:d},{queue:c,duration:f,easing:b[8]})}function ea(d,f){y.animate({height:d},{queue:c,duration:f,easing:b[8]})}function aa(){b[6]?s.css("margin-top",Q(h,c)):s.css("margin-left",Q(h,l))}function Q(d,f){for(var g=0,c=d-(b[11]&&!b[21]?1-b[40]:1),h=b[11]&&!b[21]?h=b[40]:0,e=0;e<=c;e++)g=f?g-v.eq(e+h).outerWidth(l):g-v.eq(e+h).outerHeight(l);return g}function ga(){b[11]&&!b[21]?(h>
n&&(h=0),h<1-b[40]&&(h=q-b[40])):(h>n&&(h=0),0>h&&(h=n));h!=n||b[21]||X(c);b[24]||$(h);aa();t=l;b[17]&&U&&(window.location.hash=b[15][h]);w||(a=h+1,1>a&&(a+=q),a>q&&(a-=q),L(r.eq(h),a),b[11]&&!b[21]&&(h<b[40]&&L(v.eq(0>h?h+b[40]:h-b[40]),a),h>n-b[40]&&L(v.eq(b[40]+h-n-1),a)))}function L(d,f){k.isFunction(b[30])&&b[30].call(d,f)}function R(d,f){k.isFunction(b[29])&&b[29].call(d,f)}function S(d,f){var c=h;switch(d){case "next":c=f>=n?b[11]?c+1:0==h?1:0:c+1;break;case "prev":c=0>=c?b[11]?c-1:h==n?n-
1:n:c-1;break;case "first":c=0;break;case "last":c=n;break;default:c=parseInt(d)}return c}function D(d,f,g,h){var e=r.eq(d),n=w?b[22]?b[23]:parseInt(0.4*b[23]):g,q=d+1;ka(b[25][d])?(e.html(" ").append(k(new Image).attr("src",b[25][d])),Z(e,function(c){function g(e,p){p++;var r=e.width(),m=e.height(),s=e.parent().width();0==r&&20!=p?setTimeout(function(){g(e,p)},1):(e.attr({oldheight:m,oldwidth:r}),r>s&&e.animate({width:s,height:m/r*s},0).parent().animate({height:m/r*s},0).css("height","auto"),k.isFunction(b[28])&&
b[28].call(k(c),q,l),ha(d,e.parent(),h),f&&K(d,n))}var e=k(c).children();g(e,0)})):e.load(b[25][d],function(g,e,l){"error"!=e&&k(this).html()||k(this).html("Sorry but there was an error: "+(l.status||"no content")+" "+l.statusText);ha(d,k(this),h);f&&aa();"error"!=e&&k.isFunction(b[28])&&b[28].call(k(this),q,c);f&&K(d,n)})}function ha(d,c,g){k.isFunction(g)&&g();Y();b[11]&&!b[21]&&(d<b[40]&&v.eq(0>d?d+b[40]:d-b[40]).replaceWith(k(c).clone()),d>n-b[40]&&v.eq(b[40]+d-n-1).replaceWith(k(c).clone()),
v=s.children("li"))}function ca(d,f){if(d!=h&&!A&&t){G=c;b[24]&&$(S(d,x));t=!f;var g=f||b[9]||!b[17]?b[23]:b[23]*(b[18]/b[7]),e=S(d,x);e>n&&(e=0);0>e&&(e=n);if(b[25]&&b[25][e])D(e,c,g,function(){b[25][e]=c;t=l;aa();ca(e,l)});else{K(e,b[23]);var p=r.eq(e);R(p,e+1);if(b[22])p.clone().prependTo(y).css({"z-index":"100000",position:"absolute","list-style":"none",top:"0",left:"0"}).hide().fadeIn(b[23],function(){W&&this.style.removeAttribute("filter");w=t=l;C(e,c,c,c);k(this).remove();b[17]&&f&&(window.location.hash=
b[15][h]);w=c;L(p,e+1)});else{var q=parseInt(0.6*g),g=g-q,m=r.eq(e).children();M||(M=0);r.eq(M).children().stop();r.eq(M).children().fadeTo(g,0,function(){w=t=l;C(e,c,c,c);t=!f;m.stop().fadeTo(0,0).each(function(){var b=k(this).data("contentOpacity")?k(this).data("contentOpacity"):1;k(this).fadeTo(q,b,function(){W&&this.style.removeAttribute("filter")})});setTimeout(function(){b[17]&&f&&(window.location.hash=b[15][h]);t=l;w=c;M=e;L(p,e+1)},q)})}}}}function C(d,f,e,k){if(t&&!A&&(S(d,x)!=h||T)||k){G=
c;t=f||b[9]?b[16]:l;U=f;x=h;h=S(d,x);b[24]&&$(h);var p=Math.sqrt(Math.abs(x-h)),m=parseInt(p*b[7]);f||b[9]||(m=parseInt(p*b[18]));e||(m=0);p=h;0>p&&(p+=q);p>n&&(p-=q);if(k)m=ia,N&&N--;else if(b[25]){b[25][p]&&(D(p,l,m,c),b[25][p]=c,G=l);if(!w){k=x>h?h:x;var y=x>h?x:h;N=0;ia=m;for(var u=k;u<=y;u++)u<=n&&(0<=u&&b[25][u])&&(D(u,c,m,function(){C(d,f,e,u)}),b[25][u]=c,N++)}p+1<=n&&b[25][p+1]&&(D(p+1,c,0,c),b[25][p+1]=c)}N||(0>h&&v.eq(b[40]+h),h>n&&v.eq(h-q-b[40]),w||(R(r.eq(p),p+1),b[11]&&!b[21]&&(h<b[40]&&
R(v.eq(0>h?h+b[40]:h-b[40]),p+1),(h>n-b[40]||h==-b[40])&&R(v.eq(h==-b[40]?-1:b[40]+h-n-1),p+1))),w||G||K(h,m),b[6]?(p=Q(h,c),s.animate({marginTop:p},{queue:c,duration:m,easing:b[8],complete:ga})):(p=Q(h,l),s.animate({marginLeft:p},{queue:c,duration:m,easing:b[8],complete:ga})),b[2]&&w&&parseInt(0.6*b[23]),T=c)}}function ja(b){for(var c="controlsShow controlsFadeSpeed controlsFade insertAfter firstShow lastShow vertical speed ease auto pause continuous prevNext numeric numericAttr numericText clickableAni history speedhistory autoheight customLink fade crossFade fadespeed updateBefore ajax preloadAjax startSlide ajaxLoadFunction beforeAniFunc afterAniFunc uncurrentFunc currentFunc prevHtml nextHtml loadingText firstHtml controlsAttr lastHtml autowidth slideCount resumePause".split(" "),
e=0;e<c.length;e++)if(c[e]==b)var h=e;return h}var T,s,r,v,q,h,x,n,t,U,w,G,O,V,A,W,u,B,F,ia,N,I,y=k(this),M;e(y,c);m.getOption=function(d){return b[ja(d)]};m.setOption=function(d,c){m.destroy();b[ja(d)]=c;m.init()};m.insertSlide=function(d,c,e){d&&(m.destroy(),c>q&&(c=q),d="<li>"+d+"</li>",c&&0!=c?r.eq(c-1).after(d):s.prepend(d),(c<=F||!c||0==c)&&F++,b[15].length<c&&(b[15].length=c),b[15].splice(c,0,e||parseInt(c,10)+1),m.init())};m.removeSlide=function(c){c--;m.destroy();r.eq(c).remove();b[15].splice(c,
1);c<F&&F--;m.init()};m.goToSlide=function(b){E(b==parseInt(b)?b-1:b,l)};m.block=function(){t=c};m.unblock=function(){t=l};m.startAuto=function(){b[11]||m.setOption("continuous",l);b[9]=l;B=J(b[10])};m.stopAuto=function(){b[9]=c;clearTimeout(B);I=c};m.destroy=function(){F=h;u&&u.remove();A=l;k(b[20]).die("click");if(b[11]&&!b[21])for(a=1;a<=b[40];a++)v.eq(a-1).remove(),v.eq(-a).remove()};m.init=function(){A&&e(y,F)};m.adjust=function(b){b||(b=0);Y();K(i,b)};m.getValue=function(b){switch(b){case "currentSlide":return h+
1;case "totalSlides":return q;case "clickable":return t;case "destroyed":return A;case "autoAnimation":return I}}})}})(xtd_jQuery);

(function(a){function M(a,q){a.thumbnailScroller(q);return a}function O(a,q){var m={itemsalign:"left",scrollerType:"hoverPrecise",scrollerOrientation:"horizontal",thumbs:a.thumbsource,"hover.mouseOverEffect":!0,"hover.mouseOverEffectDuration":1E3,"hover.mouseOverEffectEasing":"swing",opacity:1,"hover.opacity":1,"active.opacity":1,"back.opacity":1,"next.opacity":1},l;for(l in m){var t=q+"."+l;if("back.opacity"==l||"next.opacity"==l)t=q+"_"+l;if(a[t]&&"opacity"!=l&&"scrollerOrientation"!=l)m[l]=a[t];
else if(t=q+"item."+l,void 0!=a[t]&&(m[l]=a[t]),-1<q.indexOf("thumbscroll")||-1<q.indexOf("navbar"))t=q+"itemthumb."+l,void 0!=a[t]&&(m[l]=a[t])}m.scrollerOrientation=a[q+"item.orientation"]?a[q+"item.orientation"]:"horizontal";-1<q.indexOf("bullets")&&"noScroll"==m.scrollerType;return m}var m=a.browser.msie&&10>parseInt(a.browser.version,10);a.fn.jQuerySlider=function(){function N(a,e,b){var c={},d={},f=b.data("xtd:initial");switch(a){case "fadeIn":c.opacity=f.opacity;d.opacity=0;break;case "slideFromLeft":"auto"==
f.right?(c.left=f.left,d.left=-(b.outerWidth(!0)+z+A)+"px"):(c.right=f.right,d.right=e.innerWidth()+z+A+"px");break;case "slideFromRight":"auto"==f.right?(c.left=f.left,d.left=e.innerWidth()+B+C+"px"):(c.right=f.right,d.right=-(b.outerWidth(!0)+B+C)+"px");break;case "slideFromTop":"auto"==f.bottom?(c.top=f.top,d.top=-(b.outerHeight(!0)+D+E)+"px"):(c.bottom=f.bottom,d.bottom=e.innerHeight()+D+E+"px");break;case "slideFromBottom":"auto"==f.bottom?(c.top=f.top,d.top=e.innerHeight()+F+G+"px"):(c.bottom=
f.bottom,d.bottom=-(b.outerHeight(!0)+F+G)+"px")}return{"in":c,out:d}}function q(a,c,b){a.data("xtd:initial",{left:a.css("left"),right:a.css("right"),top:a.css("top"),bottom:a.css("bottom"),opacity:b});var d=N(e[c+".mouseOutEffect"],f,a),g=e[c+".mouseOutEffectDuration"],h=e[c+".mouseOutEffectEasing"];a.animate(d.out,0);p.mouseenter(function(a){return function(c){a.animate(d["in"],parseInt(g),h)}}(a)).mouseleave(function(a){return function(c){a.animate(d.out,parseInt(g),h)}}(a))}function K(){m?(H.children().filter(".play").css({display:"none"}),
H.children().filter(".pause").css({display:"block"})):(a("div[id^='"+c+"_playpause']").children().filter(".play").css({display:"none"}),a("div[id^='"+c+"_playpause']").children().filter(".pause").css({display:"block"}))}function l(){m?(H.children().filter(".play").css({display:"block"}),H.children().filter(".pause").css({display:"none"})):(a("div[id^='"+c+"_playpause']").children().filter(".play").css({display:"block"}),a("div[id^='"+c+"_playpause']").children().filter(".pause").css({display:"none"}))}
function t(c){var b=0;c.children().each(function(c){b+=a(this).outerWidth(!0)});return b}var r=a,c=a(this).attr("id");r.globalEval("var global = this;");var e=global[c+"_json"],e=r.extend({},JQuerySlider_init,e);e.autoheight=!1;e.autowidth=!1;e.clickableAni=!0;e.updateBefore=!0;e.clickableAni=!1;e.controlsShow=!1;e.numeric=!1;e.hideOnMouseOut=!0;e.crossFade=!1;e.fadeDuration=parseInt(e.fadeDuration);e.speed=parseInt(e.speed);e.resumePause=e.stopAtInteraction?!1:parseInt(e.resumeDuration);e.pause=
parseInt(e.pause);e.fadespeed=e.speed;e.fade="fade"==e.sliderEffect?!0:!1;var r=["innernavbar","innerbutton.back","innerbutton.next","innerplaypause"],n=[["navbar","bullets","numbers"],["back"],["next"],["playpause"]],u=[["navbar","bullets","numbers"]],f=a("#"+c+"Container");f.children().children("ul").children("li").children("div").children("a:only-child");f.children().children("ul").children("li[data-link]").each(function(){var c=a(this);c.find("a").click(function(a){a.preventDefault()});c.click(function(){var a=
c.attr("data-link"),b=c.attr("data-target");b&&"undefined"!=b||(b="_self");window.open(a,b)});c.mouseenter(function(c){a(this).css("cursor","pointer")}).mouseleave(function(c){a(this).css("cursor","default")})});for(var b=0;b<n[0].length;b++){var g=e["inner"+n[0][b]+".itemsalign"],h=a("div[id='"+c+"_"+n[0][b]+"_in'] ul");if(h.length){h.parent().cleanWhitespace();h.children().cleanWhitespace();h.children().css("display","block");var s=e["inner"+n[0][b]+"item.orientation"];0<h.length&&s&&"horizontal"==
s?(s=t(h),h.css("width",s+"px"),g&&("left"!=g&&"center"!=g||h.css("margin-right","auto"),"right"!=g&&"center"!=g||h.css("margin-left","auto"))):(h.css("float","left"),h.children().css({"float":"left",clear:"left"}))}}for(var d in e)if(b=d.match(/^content_(.*)\.opacity/i))b=f.find("."+b[1]),b.data("contentOpacity",e[d]),b.applyOpacity(e[d]);var v,w;e.beforeAniFunc=function(b){if(m)for(var e=0;e<n[0].length;e++)v=a("#"+c+"_"+n[0][e]+"_in ul").children("li"),w=a("#"+c+"_"+n[0][e]+" ul").children("li"),
v.add(w).each(function(){a(this).children().each(function(){a(this).is(".active")&&"block"==a(this).css("display")&&(a(this).css("display","none"),a(this).parent().children("a").not(".active, .hover").css("display","block"))})}),v.eq(b-1).children().not(".active").css("display","none"),v.eq(b-1).children().filter(".active").css("display","block"),w.eq(b-1).children().not(".active").css("display","none"),w.eq(b-1).children().filter(".active").css("display","block");else for(e=0;e<n[0].length;e++)w=
a("#"+c+"_"+n[0][e]+" ul").children("li"),w.children().removeClass("active"),w.eq(b-1).children().addClass("active"),v=a("#"+c+"_"+n[0][e]+"_in ul").children("li"),v.children().removeClass("active"),v.eq(b-1).children().addClass("active")};e.afterAniFunc=function(a){!1==e.loop&&(k&&!0==k.getValue("autoAnimation")&&a==k.getValue("totalSlides"))&&(l(),k.stopAuto(),k.trigger)};m&&(a("div[id^='"+c+"_numbers']"),a("div[id^='"+c+"_bullets'] ul, div[id^='"+c+"_numbers'] ul, div[id^='"+c+"_navbar'] ul").children("li").each(function(b){b=
a(this).children();a(this).parent().parent().is(a("div[id^='"+c+"_bullets']"))&&b.css({fontSize:"0px",lineHeight:"0px"});b.css("z-index","1");b.css("position","relative");var d=b.clone();d.addClass("active");a(this).append(d);d.css("display","none");var f=b.clone();f.addClass("hover");a(this).append(f);f.css("display","none");b.addClass("normal");b.css("display","block");if(a(this).parent().parent().is(a("div[id^='"+c+"_bullets'], div[id^='"+c+"_numbers']"))){var g=d.getBgImage(e.gifPath,d);g&&(d.append(g),
d.css("background-image","none"));if(d=f.getBgImage(e.gifPath,f))f.append(d),f.css("background-image","none");if(f=b.getBgImage(e.gifPath,b))b.append(f),b.css("background-image","none")}}));b=f.outerWidth(!0);d=f.outerHeight(!0);var p=a("<div/>");p.attr("id",""+c+"ContainerJS");p.css("width",b);p.css("height",d);p.css("overflow","hidden");p.css("position",f.css("position"));p.css("top",f.css("top"));p.css("left",f.css("left"));p.css("bottom",f.css("bottom"));p.css("right",f.css("right"));"left"!=
e.align&&"center"!=e.align||p.css("margin-right","auto");"right"!=e.align&&"center"!=e.align||p.css("margin-left","auto");f.wrap(p).css("overflow","visible");var p=a("#"+c+"ContainerJS"),k=a(this).sudoSlider(e),z=parseInt(f.css("margin-left")),B=parseInt(f.css("margin-right")),F=parseInt(f.css("margin-bottom")),D=parseInt(f.css("margin-top")),z=isNaN(z)?0:z,B=isNaN(B)?0:B,F=isNaN(F)?0:F,D=isNaN(D)?0:D,A=parseInt(f.css("border-left-width")),C=parseInt(f.css("border-right-width")),G=parseInt(f.css("border-bottom-width")),
E=parseInt(f.css("border-top-width")),A=isNaN(A)?0:A,C=isNaN(C)?0:C,G=isNaN(G)?0:G,E=isNaN(E)?0:E,b=parseInt(f.css("padding-left"));d=parseInt(f.css("padding-right"));g=parseInt(f.css("padding-bottom"));h=parseInt(f.css("padding-top"));b=isNaN(b)?0:b;d=isNaN(d)?0:d;var g=isNaN(g)?0:g,h=isNaN(h)?0:h,I,J=0,h=f.css("padding-left")?parseInt(f.css("padding-left").replace("px","")):0,s=f.css("padding-right")?parseInt(f.css("padding-right").replace("px","")):0;I=f.css("padding-top")?parseInt(f.css("padding-top").replace("px",
"")):0;J=f.css("padding-bottom")?parseInt(f.css("padding-bottom").replace("px","")):0;m&&7>parseInt(a.browser.version,10)&&(b=a("<div/>"),b.css({top:"0px",left:"0px",position:"absolute"}),f.prepend(b),b.css("background-image",f.css("background-image")),b.css("width",f.outerWidth()),b.css("height",f.outerHeight()),f.css("background-image","none"));for(b=0;b<r.length;b++)for(g=0;g<n[b].length;g++){d=a("#"+c+"_"+n[b][g]+"_in");d.css("z-index",99999);var P=d.css("left")?parseInt(d.css("left").replace("px",
"")):0,Q=d.css("right")?parseInt(d.css("right").replace("px","")):0,R=d.css("top")?parseInt(d.css("top").replace("px","")):0,S=d.css("bottom")?parseInt(d.css("bottom").replace("px","")):0;"auto"!=d.css("left")&&d.css("left",P+h+"px");"auto"!=d.css("right")&&d.css("right",Q+s+"px");"auto"!=d.css("top")&&d.css("top",R+I+"px");"auto"!=d.css("bottom")&&d.css("bottom",S+J+"px");a("#"+c+"").parent().append(d)}var x=a("div[id^='"+c+"_back']"),y=a("div[id^='"+c+"_next']"),b=a("#"+c+"_playpause_in").add(a("#"+
c+"_playpause")).children().filter(".play");d=a("#"+c+"_playpause_in").add(a("#"+c+"_playpause")).children().filter(".pause");m&&(b.attr("id",c+"_playpause_in_play"),d.attr("id",c+"_playpause_in_pause"),b=a("#"+c+"_playpause_in_play").add("#"+c+"_playpause_play"),d=a("#"+c+"_playpause_in_pause").add("#"+c+"_playpause_pause"),g=function(b,c){b.each(function(b){b=a('<div id="'+a(this).attr("id")+'_wrapper"></div>');b.attr("class",a(this).attr("class"));var e=a(this).clone(),d=a(this).clone();e.addClass("normal");
e.attr("style","");e.css("position","static");e.css("display","block");e.appendTo(b);d.addClass("hover");d.attr("style","");d.css("position","static");d.css("display","none");d.attr("id",d.attr("id"));d.appendTo(b);b.css("top",a(this).css("top"));b.css("bottom",a(this).css("bottom"));b.css("left",a(this).css("left"));b.css("right",a(this).css("right"));b.css("position","absolute");b.css("width",a(this).css("width"));b.css("height",a(this).css("height"));a(this).replaceWith(b);c.push(b)})},h=[],s=
[],I=[],J=[],g(x,h),g(y,s),g(b,I),g(d,J),x=a(h[0]),y=a(s[0]),b=a(I[0]),d=a(J[0]),b.css("position","static"),d.css("position","static"),x.css("z-index",1E5),y.css("z-index",1E5),b.css("z-index",1E5));a("div[id^='"+c+"_playpause_in']").css("z-index",1E5);a(x).add(y).add(b).add(d).hover(function(b){b=a(this);m?(b.children().filter(".hover").css("display","block"),b.children().filter(".normal").css("display","none")):b.addClass("hover")}).mouseleave(function(b){b=a(this);m?(b.children().filter(".hover").css("display",
"none"),b.children().filter(".normal").css("display","block")):b.removeClass("hover")});b=a("div[id^='"+c+"_numbers']").css("background-image");d=a("div[id^='"+c+"_navbar']").css("background-image");g=a("div[id^='"+c+"_bullets']").css("background-image");f.children().fixPng(e.gifPath,!1);f.children("JQSlider").children().filter("ul").fixPng(e.gifPath,!0);a("div[id^='"+c+"_numbers']").css("filter","");a("div[id^='"+c+"_numbers']").css("background-image",b);a("div[id^='"+c+"_navbar']").css("filter",
"");a("div[id^='"+c+"_navbar']").css("background-image",d);a("div[id^='"+c+"_bullets']").css("filter","");a("div[id^='"+c+"_bullets']").css("background-image",g);x.click(function(b){b.preventDefault();e.stopAtInteraction&&(k.stopAuto(),l());if(e.loop||1!=k.getValue("currentSlide"))e.loop||2!=k.getValue("currentSlide")||a(this).hide(),y.show(),k.goToSlide("prev")});y.click(function(b){b.preventDefault();e.stopAtInteraction&&(k.stopAuto(),l());if(e.loop||k.getValue("currentSlide")!=k.getValue("totalSlides"))e.loop||
k.getValue("currentSlide")!=k.getValue("totalSlides")-1||a(this).hide(),x.show(),k.goToSlide("next")});for(b=0;b<r.length;b++)for(g=0;g<n[b].length;g++)d=a("#"+c+"_"+n[b][g]+"_in_wrapper"),d.length||(d=a("#"+c+"_"+n[b][g]+"_in")),h=u[b]?"inner"+u[b][g]:r[b],s=1,e[h+".opacity"]&&(s=parseFloat(e[h+".opacity"])),e[h+".hideOnMouseOut"]&&d.length&&q(d,h,s);var H=a("#"+c+"_playpause_in");H.click(function(b){b.preventDefault();"block"==a(this).children().filter(".play").css("display")?(!1==k.getValue("autoAnimation")&&
k.startAuto(),K()):(k.stopAuto(),l())});!0==e.auto?K():(k.stopAuto(),l());for(b=0;b<n[0].length;b++)(r=a("div[id='"+c+"_"+n[0][b]+"_in'] ul li"))&&0!=r.length&&(r.children().css("float","left"),r.children().css("clear","left"),r.hover(function(b){m?"block"!=a(this).children().filter(".active").css("display")&&(a(this).children().not(".hover").css("display","none"),a(this).children().filter(".hover").css("display","block")):a(this).children().addClass("hover")},function(b){if(m){var c;a(this).parent().children().children().filter(".active").each(function(b){"block"==
a(this).css("display")&&(c=a(this).parent())});a(this).children("a").filter(".hover").css("display","none");!c||c.is(this)?a(this).children("a").filter(".active").css("display","block"):a(this).children("a").not(".hover, .active").css("display","block")}else a(this).children("a").removeClass("hover")}));a("div[id^='"+c+"_numbers'] ul, div[id^='"+c+"_bullets'] ul, div[id^='"+c+"_navbar'] ul").children("li").click(function(b){b.preventDefault();e.stopAtInteraction&&(k.stopAuto(),l());k.goToSlide(a(this).index()+
1)});r=[];u=["numbers","navbar","innernumbers","innernavbar"];for(b=0;b<u.length;b++)if(d=0<=u[b].indexOf("inner")?u[b].replace("inner","")+"_in":u[b],d=a("div[id='"+c+"_"+d+"']"),0<d.length)try{var L=M(d,O(e,u[b]));k.bind("xtd:beforeEffect",function(a,b){L.selectThumb(b)});r.push(L)}catch(T){alert(T)}return k}})(xtd_jQuery);


/*
Thumbnail scroller jQuery plugin
Author: malihu [http://manos.malihu.gr]
Homepage: manos.malihu.gr/jquery-thumbnail-scroller
*/
(function(e){var w=e.browser.msie&&10>parseInt(e.browser.version,10);e.fn.thumbnailScroller=function(a){function x(){return 1!=(a["active.opacity"]==a["hover.opacity"]==a.opacity)}function u(c){w||(c.children("a").removeClass("hover"),c.children("a").removeClass("normal"),c.children("a").addClass("active"));x()&&c.children("a").filter(".active").find("img").not(".bgImg").css("opacity",a["active.opacity"])}function y(c){w||(c.children("a").removeClass("hover"),c.children("a").addClass("normal"));x()&&
(c.children("a").hasClass("active")&&"none"!=c.children("a").filter(".active").css("display")?c.children("a").filter(".active").find("img").not(".bgImg").css("opacity",a["active.opacity"]):c.children("a").filter(".normal").find("img").not(".bgImg").css("opacity",a.opacity))}function B(c){var b=d.children().eq(f);w||(b.children("a").removeClass("active"),b.children("a").addClass("normal"));x()&&b.children("a").filter(".normal").find("img").not(".bgImg").css("opacity",a.opacity);f=c;e(this).data("mouseover")?
"hoverPrecise"!=a.scrollerType&&s(c):s(c);c=d.children().eq(c);u(c)}function s(c){c=d.children().eq(c);var e=d.children().length,e="horizontal"==a.scrollerOrientation?b.width()/c.outerWidth(!0):b.height()/c.outerHeight(!0),e=Math.floor(e/2),f=-c.position().left,f=f+e*c.outerWidth(!0);g+f<b.width()&&(f=-(g-b.width()));0<f&&(f=0);var k=-c.position().top,k=k+e*c.outerHeight(!0);h+k<b.height()&&(k=-(h-b.height()));0<k&&(k=0);"horizontal"==a.scrollerOrientation?d.stop().animate({left:f},a.scrollSpeed,
a.scrollEasing,void 0):d.stop().animate({top:k},a.scrollSpeed,a.scrollEasing,void 0)}function H(){var c=d.position().left,e=d.position().top,c=g+(c-b.width()),e=h+(e-b.height());"horizontal"==a.scrollerOrientation?c>=b.width()?d.stop().animate({left:"-="+b.width()},a.scrollSpeed,a.scrollEasing,function(){}):d.stop().animate({left:b.width()-g},a.scrollSpeed,a.scrollEasing):e>=b.height()?d.stop().animate({top:"-="+b.height()},a.scrollSpeed,a.scrollEasing,function(){}):d.stop().animate({top:b.height()-
h},a.scrollSpeed,a.scrollEasing)}function I(){var c=d.position().left;b.width();var e=d.position().top;b.height();"horizontal"==a.scrollerOrientation?0>=c+b.width()?d.stop().animate({left:"+="+b.width()},a.scrollSpeed,a.scrollEasing,function(){}):d.stop().animate({left:0},a.scrollSpeed,a.scrollEasing):0>=e+b.height()?d.stop().animate({top:"+="+b.height()},a.scrollSpeed,a.scrollEasing,function(){}):d.stop().animate({top:0},a.scrollSpeed,a.scrollEasing)}function C(a){var b=curtop=0;if(a.offsetParent)for(b=
a.offsetLeft,curtop=a.offsetTop;a=a.offsetParent;)b+=a.offsetLeft,curtop+=a.offsetTop;return[curtop,b]}var f=0;a=e.extend({scrollerType:"hoverPrecise",scrollerOrientation:"horizontal",scrollEasing:"easeOutCirc",scrollEasingAmount:1E3,acceleration:2,scrollSpeed:400,noScrollCenterSpace:0,autoScrolling:0,autoScrollingSpeed:8E3,autoScrollingEasing:"easeInOutQuad",autoScrollingDelay:2500,thumbs:[],changed:function(a){}},a);this.nextThumb=function(){if(f<d.children().length-1){var a=d.children().eq(f);
y(a);f++;a=d.children().eq(f);u(a);s(f)}};this.prevThumb=function(){if(0<f){var a=d.children().eq(f);y(a);f--;a=d.children().eq(f);u(a);s(f)}};this.selectThumb=B;this.scrollToIndex=s;var d,m,q,r,g,h,b;return this.each(function(){function c(){"horizontal"==a.scrollerOrientation?n<b.width()/2&&0<=d.position().left?d.stop(!0,!0).css("left",0):n>b.width()/2&&d.position().left<=-(g-b.width())?d.stop(!0,!0).css("left",-(g-b.width())):n<=b.width()/2-a.noScrollCenterSpace||n>=b.width()/2+a.noScrollCenterSpace?
(D=Math.round(Math.cos(n/b.width()*Math.PI)*(v+a.acceleration)),d.stop(!0,!0).animate({left:"+="+D},v,"linear")):d.stop(!0,!0):p<b.height()/2&&0<=d.position().top?d.stop(!0,!0).css("top",0):p>b.height()/2&&d.position().top<=-(h-b.height())?d.stop(!0,!0).css("top",-(h-b.height())):p<=b.height()/2-a.noScrollCenterSpace||p>=b.height()/2+a.noScrollCenterSpace?(E=Math.cos(p/b.height()*Math.PI)*(v+a.acceleration),d.stop(!0,!0).animate({top:"+="+E},v,"linear")):d.stop(!0,!0)}function f(){d.delay(a.autoScrollingDelay).animate({left:-(g-
b.width()),top:-(h-b.height())},a.autoScrollingSpeed,a.autoScrollingEasing,function(){d.animate({left:0,top:0},a.autoScrollingSpeed,a.autoScrollingEasing,function(){F++;1<a.autoScrolling&&a.autoScrolling!=F&&f()})})}function G(){r.show();q.show();q.click(function(a){a.preventDefault();H()});r.click(function(a){a.preventDefault();I()})}b=e(this);this.scrollToIndex=s;var k=!1,z;0<e(this).attr("id").indexOf("thumbscroll")&&(k=!0,z="thumbscroll");0<e(this).attr("id").indexOf("navbar")&&(k=!0,z="navbar");
e(this).hover(function(){a.mouseChanged&&a.mouseChanged("in")},function(){a.mouseChanged&&a.mouseChanged("out")});m=e("<div />");b.append(m);m.append(b.children("ul").clone(!0,!0));b.children("ul").first().remove();d=m.children("ul");k&&d.children().each(function(b){var d=a.thumbs,c;if("navbar"!=z){var f=e(this).children("a").width(),g=e(this).children("a").height();c=e("<img/>").attr("src",d[b].src);e(this).children("a").append(c);b=parseInt(c.css("border-left-width"))-parseInt(c.css("padding-left"));
var d=parseInt(c.css("border-right-width"))-parseInt(c.css("padding-right")),h=parseInt(c.css("border-top-width"))-parseInt(c.css("padding-top")),k=parseInt(c.css("border-bottom-width"))-parseInt(c.css("padding-bottom"));e(this).children("a").children("img").css({width:f-(b+d)+"px",height:g-(h+k)+"px"});e(this).children("a").children("img").attr({width:f-(b+d),height:g-(h+k)})}var l=e(this);c=l.find("img").not("bgImg");c.css("opacity",a.opacity);l.children("a").first();parseFloat(a["hover.mouseOverEffectDuration"]);
l.hover(function(){!0==a["hover.mouseOverEffect"]?"block"!=l.children("a").filter(".active").css("display")?c.stop().animate({opacity:a["hover.opacity"]},a["hover.mouseOverEffectDuration"],a["hover.mouseOverEffectEasing"]):u(l):"block"!=l.children("a").filter(".active").css("display")&&(w||(l.children("a").removeClass("normal"),l.children("a").addClass("hover")),x()&&l.children("a").filter(".hover").find("img").not(".bgImg").css("opacity",a["hover.opacity"]))},function(){!0==a["hover.mouseOverEffect"]?
"block"!=l.children("a").filter(".active").css("display")?c.stop().animate({opacity:a.opacity},parseFloat(a["hover.mouseOverEffectDuration"]),a["hover.mouseOverEffectEasing"]):u(l):"block"!=l.children("a").filter(".active").css("display")&&y(l)})});m.css("overflow","hidden");m.css({width:e(this).width(),position:"relative",height:e(this).height()});q=e("#"+b.attr("id").replace("_in","_next_in"));a["next.opacity"]&&q.css({opacity:a["next.opacity"]});r=e("#"+b.attr("id").replace("_in","_back_in"));
a["back.opacity"]&&r.css({opacity:a["back.opacity"]});q.add(r).hover(function(){e(this).addClass("hover")},function(){e(this).removeClass("hover")});"horizontal"==a.scrollerOrientation?(g=0,d.children("li").each(function(){g+=e(this).outerWidth(!0)}),d.css("width",g),h=d.outerHeight(!0)):(g=d.outerWidth(!0),h=0,d.children("li").each(function(){h+=e(this).outerHeight(!0)}),d.css("height",h));if(g>b.width()&&"horizontal"==a.scrollerOrientation||h>b.height()&&"vertical"==a.scrollerOrientation){var t,
n,p;switch(a.scrollerType){case "hoverAccelerate":var A,v=8;b.hover(function(){b.mousemove(function(a){t=C(this);n=a.pageX-t[1];p=a.pageY-t[0]});clearInterval(A);A=setInterval(c,v)},function(){clearInterval(A);d.stop()});r.add(q).hide();break;case "clickButtons":G();break;case "hoverPrecise":t=C(this),b.mousemove(function(c){n=c.pageX-t[1];p=c.pageY-t[0];var e=n/b.width();1<e&&(e=1);c=p/b.outerHeight();1<c&&(c=1);0.1>e&&(e=0);0.9<e&&(e=1);0.1>c&&(c=0);0.9<c&&(c=1);e=Math.round(-((g-b.width())*e));
c=Math.round(-((h-b.height())*c));"horizontal"==a.scrollerOrientation?d.stop(!0,!1).animate({left:e},a.scrollEasingAmount,a.scrollEasing):d.stop(!0,!1).animate({top:c},a.scrollEasingAmount,a.scrollEasing)}),r.add(q).hide()}a.autoScrolling&&f()}else"horizontal"==a.scrollerOrientation&&("right"==a.itemsalign?m.children("ul").css({marginRight:"0px",marginLeft:"auto"}):"center"==a.itemsalign&&m.children("ul").css({marginRight:"auto",marginLeft:"auto"}));var D,E,F=0;B(0)})}})(xtd_jQuery);